package org.example.DAO;

public class SQLSelectStrings {

	private String EmployeePayForASelectedWeekSQL = "SELECT EMP.EMP_LAST_NAME LAST_NAME, EMP.EMP_FIRST_NAME FIRST_NAME, " +
			"CASE " +
			"WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'PART TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') " +
			"THEN JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED <= 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'PART TIME' AND JOB_DESCR.JOB_TITLE  IN ('EXECUTIVE' , 'MANAGER') " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) + 50 " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED <= 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) + 50 " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED > 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * 40) + (JOB_DESCR.WAGE_RATE * 1.5 * (WEEK_HOURS.HOURS_WORKED - 40)) " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED > 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * 40) + (JOB_DESCR.WAGE_RATE * 1.5 * (WEEK_HOURS.HOURS_WORKED - 40)) + 50 " +
			"END AS PAY_FOR_SELECTED_WEEK " +
			"FROM Company.WORK_WEEK AS WORK_WEEK, " +
			"Company.EMPLOYEE EMP " +
			"LEFT JOIN Company.JOB_DESCRIPTION JOB_DESCR " +
			"ON EMP.EMP_JOB_DESCR_ID = JOB_DESCR.JOB_ID " +
			"LEFT JOIN Company.WAGE_TYPE WAGE_TYPE " +
			"ON EMP.EMP_WAGE_TYPE_ID = WAGE_TYPE.WAGE_TYPE_ID " +
			"LEFT JOIN Company.EMPLOYEE_WEEK_HOURS WEEK_HOURS " +
			"ON EMP.EMP_ID = WEEK_HOURS.EMP_ID " +
			"WHERE WORK_WEEK.WEEK_ID = ? " +
			"AND YEAR(WORK_WEEK.START_DATE) = ?";
	private String DepartmentPayForASelectedWeek = "SELECT DEPARTMENT, SUM(PAY_FOR_SELECTED_WEEK) PAY_FOR_SELECTED_WEEK " +
			"FROM (SELECT DEPT.DEPT_NAME DEPARTMENT, " +
			"CASE " +
			"WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'PART TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') " +
			"THEN JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED <= 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'PART TIME' AND JOB_DESCR.JOB_TITLE  IN ('EXECUTIVE' , 'MANAGER') " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) + 50 " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED <= 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * WEEK_HOURS.HOURS_WORKED) + 50 " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE NOT IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED > 40 " +
			"THEN (JOB_DESCR.WAGE_RATE * 40) + (JOB_DESCR.WAGE_RATE * 1.5 * (WEEK_HOURS.HOURS_WORKED - 40)) " +
			"    WHEN WAGE_TYPE.WAGE_TYPE_NAME = 'FULL TIME' AND JOB_DESCR.JOB_TITLE IN ('EXECUTIVE' , 'MANAGER') AND WEEK_HOURS.HOURS_WORKED > 40 "  +
			"THEN (JOB_DESCR.WAGE_RATE * 40) + (JOB_DESCR.WAGE_RATE * 1.5 * (WEEK_HOURS.HOURS_WORKED - 40)) + 50 " +
			"END AS PAY_FOR_SELECTED_WEEK    " +
			"FROM Company.WORK_WEEK AS WORK_WEEK, " +
			"Company.EMPLOYEE EMP " +
			"LEFT JOIN Company.JOB_DESCRIPTION JOB_DESCR " +
			"ON EMP.EMP_JOB_DESCR_ID = JOB_DESCR.JOB_ID " +
			"LEFT JOIN Company.WAGE_TYPE WAGE_TYPE " +
			"ON EMP.EMP_WAGE_TYPE_ID = WAGE_TYPE.WAGE_TYPE_ID " +
			"LEFT JOIN Company.EMPLOYEE_WEEK_HOURS WEEK_HOURS " +
			"ON EMP.EMP_ID = WEEK_HOURS.EMP_ID " +
			"LEFT JOIN Company.DEPARTMENT DEPT " +
			"ON EMP.EMP_DEPT_ID = DEPT.DEPT_ID " +
			"WHERE WORK_WEEK.WEEK_ID = ? " +
			"AND YEAR(WORK_WEEK.START_DATE) = ?) SUB " +
			"GROUP BY DEPARTMENT";

	private String EmployeeByDepartmentHourlyRate =
			"SELECT DEPT.DEPT_NAME DEPT_NAME, EMP.EMP_LAST_NAME LAST_NAME, EMP.EMP_FIRST_NAME FIRST_NAME, " +
			"JOB_DESCR.WAGE_RATE HOURLY_RATE " +
			"FROM Company.EMPLOYEE EMP " +
			"LEFT JOIN Company.JOB_DESCRIPTION JOB_DESCR " +
			"ON EMP.EMP_JOB_DESCR_ID = JOB_DESCR.JOB_ID " +
			"LEFT JOIN Company.DEPARTMENT DEPT " +
			"ON EMP.EMP_DEPT_ID = DEPT.DEPT_ID " +
			"ORDER BY DEPT_NAME ASC, LAST_NAME ASC, FIRST_NAME ASC";
	public SQLSelectStrings() {
		// TODO Auto-generated constructor stub
	}

	public String getEmployeePayForASelectedWeekSQL() {
		return EmployeePayForASelectedWeekSQL;
	}

	public String getDepartmentPayForASelectedWeek() {
		return DepartmentPayForASelectedWeek;
	}

	public String getEmployeeByDepartmentHourlyRate() {
		return EmployeeByDepartmentHourlyRate;
	}

}
